---
# tasks file for frontend
- name: Install httpie
  package:
    name: httpie
    state: latest

- name: Install HAProxy
  yum:
    name: haproxy 
    state: latest

- name: Enable HAProxy
  service:
    name: haproxy
    state: started

- name: Configure HAProxy
  template:
    src: files/haproxy.cfg.j2
    dest: "{{ haproxy_config_file }}"
  notify: 
    - Restart HAProxy
