---
# tasks file for tomcat
- name: Install tomcat
  package:
    name: tomcat
    state: latest

- name: Enable tomcat at boot
  service:
    name: tomcat
    enabled: yes
    state: started

- name: Create ansible tomcat directory 
  file:
    path: "{{ tomcat_root }}"
    state: directory

- name: Copy static html file
  template:
    src: files/index.html.j2
    dest: "{{ tomcat_root }}/index.html"
    mode: 0644
    notify: Start tomcat

