---
# Common configuration for all hosts
- name: Enable yum repository
  template:
    src: "{{ yum_repo_file }}"
    dest: "{{ yum_repo_folder }}/{{ yum_repo_filename }}"
    mode: 0644
#  vars:
#    template_variable: vars/main.yml
