---
# tasks file for apache
- name: Install apache
  yum:
    name: httpd
    state: latest

- name: Enable apache at boot
  service:
    name: httpd
    enabled: yes
    state: started
  notify: 
    - Start Apache
